name: Build Verification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      # Separate steps for different OS types
      - name: Install dependencies (Linux/Mac)
        if: runner.os != 'Windows'
        run: |
          if [ "$RUNNER_OS" = "macOS" ]; then
            npm ci
          else
            npm ci --ignore-scripts
          fi
      
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: npm ci
      
      # Conditionally install dmg-license only on macOS
      - name: Install dmg-license on macOS
        if: runner.os == 'macOS'
        run: npm install dmg-license
      
      - name: Build
        run: npm run build